gantt
    title ds-sim Job Scheduling Gantt Chart
    dateFormat X
    axisFormat %s

    section large 0
    Job 19 Waiting: crit, 235, 295
    Job 19: 295, 397
    Job 24: 399, 417
    Job 25: 421, 472
    Job 31: 718, 723
    Job 34: 977, 1146
    Job 35: 1130, 6642

    section large 1
    Job 38 Waiting: crit, 1245, 1305
    Job 38: 1305, 1464

    section medium 0
    Job 4 Waiting: crit, 125, 185
    Job 4: 185, 3123
    Job 18: 235, 819

    section medium 1
    Job 9 Waiting: crit, 170, 230
    Job 9: 230, 2538
    Job 17: 233, 459
    Job 30: 647, 1072

    section medium 2
    Job 16 Waiting: crit, 229, 289
    Job 16: 289, 333
    Job 22: 355, 8348

    section medium 3
    Job 23 Waiting: crit, 394, 454
    Job 23: 454, 546
    Job 32: 786, 825
    Job 33: 881, 1164
    Job 39: 1422, 2054

    section small 0
    Job 0 Waiting: crit, 51, 111
    Job 0: 111, 313
    Job 21: 338, 894
    Job 29: 622, 2670

    section small 1
    Job 5 Waiting: crit, 137, 197
    Job 5: 197, 1978

    section small 2
    Job 6 Waiting: crit, 151, 211
    Job 6: 211, 240
    Job 20: 274, 2824

    section small 3
    Job 10 Waiting: crit, 170, 230
    Job 10: 230, 400
    Job 26: 498, 536
    Job 27: 553, 2966

    section small 4
    Job 11 Waiting: crit, 181, 241
    Job 11: 241, 1464

    section small 5
    Job 13 Waiting: crit, 205, 265
    Job 13: 265, 6540

    section tiny 0
    Job 1 Waiting: crit, 66, 126
    Job 1: 126, 2205

    section tiny 1
    Job 2 Waiting: crit, 88, 148
    Job 2: 148, 8099

    section tiny 2
    Job 3 Waiting: crit, 120, 180
    Job 3: 180, 938

    section tiny 3
    Job 7 Waiting: crit, 155, 215
    Job 7: 215, 542
    Job 28: 600, 726
    Job 37: 1232, 1277

    section tiny 4
    Job 8 Waiting: crit, 168, 228
    Job 8: 228, 763
    Job 36: 1223, 1624

    section tiny 5
    Job 12 Waiting: crit, 189, 249
    Job 12: 249, 6658

    section tiny 6
    Job 14 Waiting: crit, 216, 276
    Job 14: 276, 6451

    section tiny 7
    Job 15 Waiting: crit, 225, 285
    Job 15: 285, 3591

