gantt
    title ds-sim Job Scheduling Gantt Chart
    dateFormat X
    axisFormat %s

    section large 0
    Job 1 Waiting: crit, 50, 110
    Job 1: 110, 2588
    Job 7: 2897, 4182
    Job 8 Waiting: crit, 2947, 4182
    Job 8: 4182, 4861

    section medium 0
    Job 3 Waiting: crit, 100, 160
    Job 3: 160, 2993
    Job 5: 2707, 5623

    section medium 1
    Job 4 Waiting: crit, 144, 204
    Job 4: 204, 3673

    section small 0
    Job 0 Waiting: crit, 20, 80
    Job 0: 80, 2711
    Job 6: 2815, 5007

    section small 1
    Job 2 Waiting: crit, 75, 135
    Job 2: 135, 3402
    Job 9: 3748, 4887

